config/routes.rb
Devisetest::Application.routes.draw do

  root :to => "home#index", :as => :root

  post 'test' => 'home#test', :as => :test

  devise_for :users, :controllers => { :omniauth_callbacks => "authorizations" } do
    get 'sign_in', :to => 'sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'sessions#destroy', :as => :destroy_user_session
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :oauthable
  devise :rememberable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token['extra']['user_hash']
    if user = User.find_by_email(data["email"])
      user
    else # Create an user with a stub password.
      User.create!(:email => data["email"], :remember_me => true ) #, :password => Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
  def facebook
    @user = User.find_for_facebook_oauth(env["omniauth.auth"], current_user)

    logger.debug "USEER: " + @user.inspect

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def test
    respond_to do |f|
      f.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authorizations_helper.rb
module AuthorizationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>HOME</h1>

<p>
  <%= link_to 'Test ajax', test_url, :remote => true, :method => :post %>
</p>

<div id="placeholder"></div>

<% if current_user.nil? %>
<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
<% else %>
  Logged in:
<%= current_user.email %>
<% end %>

<hr>
<h2>User:</h2>
<%= current_user.inspect %>
<hr>
<h2>Session:</h2>
<%= session.inspect %>
<hr>
<h2>Cookies</h2>
<%= cookies.inspect %>

app/views/home/test.js.erb
$("#placeholder").append("test complete ");

app/views/layouts/application-chic.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devisetest</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <link href='http://fonts.googleapis.com/css?family=Corben:bold' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tag %>
  <style>
    body { background-color: black }
    h1 { font-family: 'Corben', arial, serif; font-size: 500%}
    h1 span.beauty { color: #FFFB00 }
    h1 span.room { color: #F77F07 }
    h1 span.chic { color: #ED817B }
  </style>
</head>
<body>

<% #=# current_user.inspect %>
<% #= # session.inspect %>
<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>

<%= yield %>

<h1><span class='beauty'>beauty</span><span class='room'>room</span><span class='chic'>chic</span></h1>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devisetest</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<% unless flash[:notice].blank? %>
<h3><%=flash[:notice]%></h3>
<% end %>

<%= yield %>

</body>
</html>